const fs = require('fs');
const path = require('path');
const { describe, it, expect } = require('./harness');
const {
  PERMISSIONS,
  buildAdminPrincipal,
  hasPermission,
  permissionsForRoles
} = require('../core/admin-auth');
const {
  MAX_INTERNAL_NOTE_LIST_LIMIT,
  INTERNAL_NOTE_ACTION,
  createPostgresInternalNoteService,
  validateInternalNoteInput,
  validateInternalNoteListInput
} = require('../core/admin/internal-notes');

function createPrincipal(role = 'maintainer', id = 'admin-1') {
  return buildAdminPrincipal({
    id,
    roles: [role],
    tenantId: 'default',
    pageId: 'page',
    authMethod: 'admin_session'
  });
}

function createFakeClientClass({ failAudit = false, noteRows = [], queries = [] } = {}) {
  return class FakeClient {
    async connect() {
      queries.push({ sql: 'CONNECT', params: [] });
    }

    async end() {
      queries.push({ sql: 'END', params: [] });
    }

    async query(sql, params = []) {
      const normalized = String(sql || '').trim();
      queries.push({ sql: normalized, params });
      if (/^INSERT INTO internal_notes/i.test(normalized)) {
        return {
          rows: [{
            id: '42',
            status: 'visible',
            created_by: params[5],
            created_at: '2026-05-12T00:00:00.000Z'
          }]
        };
      }
      if (/^INSERT INTO admin_audit_log/i.test(normalized)) {
        if (failAudit) throw new Error('audit insert failed');
        return { rows: [] };
      }
      if (/^SELECT id, target_type, target_id, body, status, created_by, created_at\s+FROM internal_notes/i.test(normalized)) {
        return { rows: noteRows };
      }
      return { rows: [] };
    }
  };
}

function findQuery(queries, pattern) {
  return queries.find(item => pattern.test(item.sql));
}

function readInternalNotesSql() {
  return fs.readFileSync(
    path.join(__dirname, '..', 'db', 'internal-notes-proposal.sql'),
    'utf8'
  );
}

function normalizeSql(sql) {
  return String(sql || '').replace(/\s+/g, ' ').trim();
}

function stripSqlComments(sql) {
  return String(sql || '')
    .split(/\r?\n/)
    .filter(line => !line.trim().startsWith('--'))
    .join('\n');
}

describe('internal notes SQL proposal', () => {
  it('is additive and idempotent for table and index creation', () => {
    const sql = stripSqlComments(readInternalNotesSql());
    const normalized = normalizeSql(sql);

    expect(normalized).toMatch(/\bCREATE TABLE IF NOT EXISTS internal_notes\b/i);
    expect(normalized).toMatch(/\bCREATE INDEX IF NOT EXISTS internal_notes_target_time_idx\b/i);
    expect(normalized).toMatch(/\bCREATE INDEX IF NOT EXISTS internal_notes_status_time_idx\b/i);
    expect((normalized.match(/\bCREATE\s+(?:TABLE|INDEX)\s+IF\s+NOT\s+EXISTS\b/gi) || []).length).toBe(3);
    expect(/\b(?:DROP|DELETE|TRUNCATE|UPDATE|INSERT|ALTER)\b/i.test(normalized)).toBeFalse();
  });

  it('defines expected columns and PostgreSQL defaults', () => {
    const normalized = normalizeSql(readInternalNotesSql());

    expect(normalized).toContain('id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(normalized).toContain('tenant_id TEXT NOT NULL');
    expect(normalized).toContain('page_id TEXT NOT NULL');
    expect(normalized).toContain('target_type TEXT NOT NULL');
    expect(normalized).toContain('target_id TEXT NOT NULL');
    expect(normalized).toContain('body TEXT NOT NULL');
    expect(normalized).toContain("status TEXT NOT NULL DEFAULT 'visible'");
    expect(normalized).toContain("created_by TEXT NOT NULL DEFAULT ''");
    expect(normalized).toContain('created_at TIMESTAMPTZ NOT NULL DEFAULT now()');
    expect(normalized).toContain("hidden_by TEXT NOT NULL DEFAULT ''");
    expect(normalized).toContain('hidden_at TIMESTAMPTZ');
    expect(normalized).toContain("hide_reason TEXT NOT NULL DEFAULT ''");
  });

  it('defines tenant, target, body, and status constraints', () => {
    const normalized = normalizeSql(readInternalNotesSql());

    expect(normalized).toContain("CHECK (tenant_id <> '')");
    expect(normalized).toContain("CHECK (page_id <> '')");
    expect(normalized).toContain("CHECK (target_type IN ('order', 'conversation', 'customer'))");
    expect(normalized).toContain("CHECK (target_id <> '')");
    expect(normalized).toContain("CHECK (body <> '')");
    expect(normalized).toContain('CHECK (char_length(body) <= 2000)');
    expect(normalized).toContain("CHECK (status IN ('visible', 'hidden'))");
  });

  it('defines expected lookup indexes with descending timeline order', () => {
    const normalized = normalizeSql(readInternalNotesSql());

    expect(normalized).toMatch(/internal_notes_target_time_idx ON internal_notes \(tenant_id, page_id, target_type, target_id, created_at DESC, id DESC\)/i);
    expect(normalized).toMatch(/internal_notes_status_time_idx ON internal_notes \(tenant_id, page_id, status, created_at DESC, id DESC\)/i);
  });
});

describe('admin internal note RBAC and validation', () => {
  it('maps internal note write only to maintainer and owner roles', () => {
    expect(permissionsForRoles(['maintainer']).includes(PERMISSIONS.INTERNAL_NOTE_WRITE)).toBeTrue();
    expect(permissionsForRoles(['owner']).includes(PERMISSIONS.INTERNAL_NOTE_WRITE)).toBeTrue();
    expect(permissionsForRoles(['support']).includes(PERMISSIONS.INTERNAL_NOTE_WRITE)).toBeFalse();
    expect(permissionsForRoles(['viewer']).includes(PERMISSIONS.INTERNAL_NOTE_WRITE)).toBeFalse();
    expect(hasPermission(createPrincipal('maintainer'), PERMISSIONS.INTERNAL_NOTE_WRITE)).toBeTrue();
    expect(hasPermission(createPrincipal('support'), PERMISSIONS.INTERNAL_NOTE_WRITE)).toBeFalse();
  });

  it('rejects invalid target type', () => {
    const result = validateInternalNoteInput({
      tenantId: 'default',
      pageId: 'page',
      targetType: 'profile',
      targetId: 'sender_1',
      body: 'safe note',
      createdBy: 'admin-1'
    });

    expect(result.ok).toBeFalse();
    expect(result.reason).toBe('invalid_target_type');
  });

  it('rejects empty target id', () => {
    const result = validateInternalNoteInput({
      tenantId: 'default',
      pageId: 'page',
      targetType: 'customer',
      targetId: '  ',
      body: 'safe note',
      createdBy: 'admin-1'
    });

    expect(result.ok).toBeFalse();
    expect(result.reason).toBe('target_id_required');
  });

  it('rejects empty body', () => {
    const result = validateInternalNoteInput({
      tenantId: 'default',
      pageId: 'page',
      targetType: 'conversation',
      targetId: 'sender_1',
      body: '  ',
      createdBy: 'admin-1'
    });

    expect(result.ok).toBeFalse();
    expect(result.reason).toBe('body_required');
  });

  it('rejects body longer than 2000 characters', () => {
    const result = validateInternalNoteInput({
      tenantId: 'default',
      pageId: 'page',
      targetType: 'order',
      targetId: '123',
      body: 'x'.repeat(2001),
      createdBy: 'admin-1'
    });

    expect(result.ok).toBeFalse();
    expect(result.reason).toBe('body_too_long');
  });

  it('rejects empty created_by', () => {
    const result = validateInternalNoteInput({
      tenantId: 'default',
      pageId: 'page',
      targetType: 'customer',
      targetId: 'sender_1',
      body: 'safe note',
      createdBy: ''
    });

    expect(result.ok).toBeFalse();
    expect(result.reason).toBe('created_by_required');
  });
});

describe('admin internal note PostgreSQL service', () => {
  it('inserts note and audit in one transaction', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    const result = await service.createNote({
      principal: createPrincipal('maintainer'),
      targetType: 'order',
      targetId: '123',
      body: 'safe internal context',
      requestContext: {
        requestId: 'req-1',
        ip: '203.0.113.10',
        userAgent: 'unit-test'
      }
    });
    const noteInsertIndex = queries.findIndex(item => /^INSERT INTO internal_notes/i.test(item.sql));
    const auditInsertIndex = queries.findIndex(item => /^INSERT INTO admin_audit_log/i.test(item.sql));
    const commitIndex = queries.findIndex(item => item.sql === 'COMMIT');

    expect(result.id).toBe('42');
    expect(result.bodyLength).toBe('safe internal context'.length);
    expect(JSON.stringify(result).includes('safe internal context')).toBeFalse();
    expect(queries.findIndex(item => item.sql === 'BEGIN') < noteInsertIndex).toBeTrue();
    expect(noteInsertIndex < auditInsertIndex).toBeTrue();
    expect(auditInsertIndex < commitIndex).toBeTrue();
    expect(findQuery(queries, /^ROLLBACK$/)).toBe(undefined);

    const auditInsert = queries[auditInsertIndex];
    const auditMetadata = JSON.parse(auditInsert.params[12]);
    expect(auditInsert.params[5]).toBe(INTERNAL_NOTE_ACTION);
    expect(auditInsert.params[6]).toBe('internal_note');
    expect(auditInsert.params[7]).toBe('42');
    expect(auditInsert.params[8]).toBe('success');
    expect(auditMetadata.target_type).toBe('order');
    expect(auditMetadata.target_id).toBe('123');
    expect(auditMetadata.body_length).toBe('safe internal context'.length);
    expect(auditMetadata.auth_method).toBe('admin_session');
  });

  it('rolls back note insert when audit insert fails', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ failAudit: true, queries })
    });

    let failed = false;
    try {
      await service.createNote({
        principal: createPrincipal('owner'),
        targetType: 'customer',
        targetId: 'sender_1',
        body: 'safe note'
      });
    } catch (err) {
      failed = true;
      expect(err.message).toBe('audit insert failed');
    }

    expect(failed).toBeTrue();
    expect(Boolean(findQuery(queries, /^INSERT INTO internal_notes/i))).toBeTrue();
    expect(Boolean(findQuery(queries, /^INSERT INTO admin_audit_log/i))).toBeTrue();
    expect(Boolean(findQuery(queries, /^ROLLBACK$/))).toBeTrue();
    expect(Boolean(findQuery(queries, /^COMMIT$/))).toBeFalse();
  });

  it('denies support without inserting a note and records denied audit', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    let failed = false;
    try {
      await service.createNote({
        principal: createPrincipal('support', 'support-1'),
        targetType: 'customer',
        targetId: 'sender_1',
        body: 'safe note'
      });
    } catch (err) {
      failed = true;
      expect(err.statusCode).toBe(403);
    }

    const auditInsert = findQuery(queries, /^INSERT INTO admin_audit_log/i);
    const metadata = JSON.parse(auditInsert.params[12]);
    expect(failed).toBeTrue();
    expect(Boolean(findQuery(queries, /^INSERT INTO internal_notes/i))).toBeFalse();
    expect(auditInsert.params[8]).toBe('denied');
    expect(metadata.reason).toBe('permission_denied');
    expect(metadata.required_permission).toBe(PERMISSIONS.INTERNAL_NOTE_WRITE);
    expect(Boolean(findQuery(queries, /^COMMIT$/))).toBeTrue();
  });

  it('audits invalid input without inserting a note', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    let failed = false;
    try {
      await service.createNote({
        principal: createPrincipal('maintainer'),
        targetType: 'profile',
        targetId: 'sender_1',
        body: 'safe note'
      });
    } catch (err) {
      failed = true;
      expect(err.code).toBe('invalid_target_type');
    }

    const auditInsert = findQuery(queries, /^INSERT INTO admin_audit_log/i);
    const metadata = JSON.parse(auditInsert.params[12]);
    expect(failed).toBeTrue();
    expect(Boolean(findQuery(queries, /^INSERT INTO internal_notes/i))).toBeFalse();
    expect(auditInsert.params[8]).toBe('denied');
    expect(metadata.reason).toBe('invalid_target_type');
    expect(Boolean(findQuery(queries, /^COMMIT$/))).toBeTrue();
  });

  it('rejects unresolved actor before inserting a note', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    let failed = false;
    try {
      await service.createNote({
        principal: buildAdminPrincipal({
          id: '',
          roles: ['owner'],
          tenantId: 'default',
          pageId: 'page',
          authMethod: 'admin_session'
        }),
        targetType: 'customer',
        targetId: 'sender_1',
        body: 'safe note'
      });
    } catch (err) {
      failed = true;
      expect(err.code).toBe('created_by_required');
      expect(err.statusCode).toBe(500);
    }

    const auditInsert = findQuery(queries, /^INSERT INTO admin_audit_log/i);
    const metadata = JSON.parse(auditInsert.params[12]);
    expect(failed).toBeTrue();
    expect(Boolean(findQuery(queries, /^INSERT INTO internal_notes/i))).toBeFalse();
    expect(auditInsert.params[8]).toBe('error');
    expect(metadata.reason).toBe('created_by_required');
    expect(Boolean(findQuery(queries, /^COMMIT$/))).toBeTrue();
  });

  it('keeps note body and raw sensitive fields out of audit metadata', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });
    const noteBody = 'do not leak this note body token DATABASE_URL 0987654321 address 12 Tran Phu';

    await service.createNote({
      principal: createPrincipal('maintainer'),
      targetType: 'conversation',
      targetId: 'sender_1',
      body: noteBody
    });

    const auditInsert = findQuery(queries, /^INSERT INTO admin_audit_log/i);
    const metadataText = auditInsert.params[12];
    expect(metadataText).toContain('"target_type":"conversation"');
    expect(metadataText).toContain('"target_id":"sender_1"');
    expect(metadataText).toContain('"body_length"');
    expect(metadataText.includes(noteBody)).toBeFalse();
    expect(metadataText.includes('do not leak this note body')).toBeFalse();
    expect(metadataText.includes('DATABASE_URL')).toBeFalse();
    expect(metadataText.includes('0987654321')).toBeFalse();
    expect(metadataText.includes('12 Tran Phu')).toBeFalse();
    expect(metadataText.includes('raw_customer')).toBeFalse();
    expect(metadataText.includes('raw_order')).toBeFalse();
    expect(metadataText.includes('raw_message')).toBeFalse();
    expect(metadataText.includes('token')).toBeFalse();
    expect(metadataText.includes('secret')).toBeFalse();
  });
});

describe('admin internal note read model', () => {
  it('validates target filters for list reads', () => {
    const valid = validateInternalNoteListInput({
      tenantId: 'default',
      pageId: 'page',
      targetType: 'Conversation',
      targetId: ' sender_1 ',
      limit: 10,
      offset: 5
    });
    const invalid = validateInternalNoteListInput({
      tenantId: 'default',
      pageId: 'page',
      targetType: 'profile',
      targetId: 'sender_1'
    });

    expect(valid.ok).toBeTrue();
    expect(valid.normalized.targetType).toBe('conversation');
    expect(valid.normalized.targetId).toBe('sender_1');
    expect(invalid.ok).toBeFalse();
    expect(invalid.reason).toBe('invalid_target_type');
  });

  it('lists only visible notes by default for the requested target', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    const result = await service.listNotes({
      targetType: 'customer',
      targetId: 'sender_1'
    });

    const select = findQuery(queries, /^SELECT id, target_type, target_id, body, status, created_by, created_at/i);
    expect(result.targetType).toBe('customer');
    expect(result.targetId).toBe('sender_1');
    expect(result.visibleOnly).toBeTrue();
    expect(select.sql).toMatch(/\btenant_id = \$1\b/i);
    expect(select.sql).toMatch(/\bpage_id = \$2\b/i);
    expect(select.sql).toMatch(/\btarget_type = \$3\b/i);
    expect(select.sql).toMatch(/\btarget_id = \$4\b/i);
    expect(select.sql).toMatch(/\bstatus = \$5\b/i);
    expect(select.params).toEqual(['default', 'page', 'customer', 'sender_1', 'visible', 25, 0]);
  });

  it('applies bounded list limits', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    const result = await service.listNotes({
      targetType: 'order',
      targetId: '123',
      limit: 10000
    });

    const select = findQuery(queries, /^SELECT id, target_type, target_id, body, status, created_by, created_at/i);
    expect(result.limit).toBe(MAX_INTERNAL_NOTE_LIST_LIMIT);
    expect(select.params[5]).toBe(MAX_INTERNAL_NOTE_LIST_LIMIT);
  });

  it('uses bounded offset pagination', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    const result = await service.listNotes({
      targetType: 'conversation',
      targetId: 'sender_1',
      limit: 2,
      offset: 4
    });

    const select = findQuery(queries, /^SELECT id, target_type, target_id, body, status, created_by, created_at/i);
    expect(result.limit).toBe(2);
    expect(result.offset).toBe(4);
    expect(select.sql).toMatch(/\bLIMIT \$6\b/i);
    expect(select.sql).toMatch(/\bOFFSET \$7\b/i);
    expect(select.params).toEqual(['default', 'page', 'conversation', 'sender_1', 'visible', 2, 4]);
  });

  it('orders notes newest first by created_at and id', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    await service.listNotes({
      targetType: 'order',
      targetId: '123'
    });

    const select = findQuery(queries, /^SELECT id, target_type, target_id, body, status, created_by, created_at/i);
    expect(select.sql).toMatch(/\bORDER BY created_at DESC, id DESC\b/i);
  });

  it('scopes list reads by tenant and page', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'tenant-b',
      pageId: 'page-b',
      Client: createFakeClientClass({ queries })
    });

    const result = await service.listNotes({
      targetType: 'customer',
      targetId: 'sender_1'
    });

    const select = findQuery(queries, /^SELECT id, target_type, target_id, body, status, created_by, created_at/i);
    expect(result.tenantId).toBe('tenant-b');
    expect(result.pageId).toBe('page-b');
    expect(select.params.slice(0, 2)).toEqual(['tenant-b', 'page-b']);
  });

  it('keeps target values parameterized in list queries', async () => {
    const queries = [];
    const maliciousTargetId = "sender_1' OR 1=1 --";
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({ queries })
    });

    await service.listNotes({
      targetType: 'customer',
      targetId: maliciousTargetId
    });

    const select = findQuery(queries, /^SELECT id, target_type, target_id, body, status, created_by, created_at/i);
    expect(select.sql.includes(maliciousTargetId)).toBeFalse();
    expect(select.params[3]).toBe(maliciousTargetId);
  });

  it('returns safe note fields without raw metadata or joined rows', async () => {
    const queries = [];
    const service = createPostgresInternalNoteService({
      databaseUrl: 'postgres://example.test/db',
      tenantId: 'default',
      pageId: 'page',
      Client: createFakeClientClass({
        queries,
        noteRows: [{
          id: 7,
          tenant_id: 'default',
          page_id: 'page',
          target_type: 'customer',
          target_id: 'sender_1',
          body: 'safe staff context',
          status: 'visible',
          created_by: 'admin-1',
          created_at: '2026-05-12T01:00:00.000Z',
          hidden_by: 'admin-2',
          hidden_at: '2026-05-12T02:00:00.000Z',
          hide_reason: 'raw reason',
          metadata: { raw_message: 'do not return' },
          raw_customer: { phone: '0987654321' },
          raw_order: { address: '12 Tran Phu' }
        }]
      })
    });

    const result = await service.listNotes({
      targetType: 'customer',
      targetId: 'sender_1'
    });
    const note = result.notes[0];

    expect(Object.keys(note).sort()).toEqual([
      'body',
      'created_at',
      'created_by',
      'id',
      'status',
      'target_id',
      'target_type'
    ]);
    expect(note.id).toBe('7');
    expect(note.body).toBe('safe staff context');
    expect(JSON.stringify(note).includes('raw_customer')).toBeFalse();
    expect(JSON.stringify(note).includes('raw_order')).toBeFalse();
    expect(JSON.stringify(note).includes('raw_message')).toBeFalse();
    expect(JSON.stringify(note).includes('hidden_by')).toBeFalse();
    expect(JSON.stringify(note).includes('tenant_id')).toBeFalse();
    expect(JSON.stringify(note).includes('page_id')).toBeFalse();
  });
});
