-- Admin auth/RBAC/audit schema proposal.
-- DO NOT apply to production without a fresh backup, dev/staging apply,
-- production owner approval, and a reviewed rollout/rollback window.
-- This file is intentionally additive and idempotent.

CREATE TABLE IF NOT EXISTS admin_users (
  id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (id <> ''),
  CHECK (status IN ('active', 'disabled'))
);

CREATE UNIQUE INDEX IF NOT EXISTS admin_users_email_unique_idx
  ON admin_users (lower(email))
  WHERE email <> '';

CREATE TABLE IF NOT EXISTS admin_roles (
  name TEXT PRIMARY KEY,
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (name IN ('viewer', 'support', 'maintainer', 'owner'))
);

CREATE TABLE IF NOT EXISTS admin_user_roles (
  user_id TEXT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  role_name TEXT NOT NULL REFERENCES admin_roles(name) ON DELETE RESTRICT,
  granted_by TEXT NOT NULL DEFAULT '',
  granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_name)
);

CREATE TABLE IF NOT EXISTS admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  tenant_id TEXT NOT NULL DEFAULT '',
  page_id TEXT NOT NULL DEFAULT '',
  actor_id TEXT NOT NULL DEFAULT '',
  actor_roles TEXT[] NOT NULL DEFAULT '{}'::text[],
  action TEXT NOT NULL,
  resource_type TEXT NOT NULL DEFAULT '',
  resource_id TEXT NOT NULL DEFAULT '',
  outcome TEXT NOT NULL,
  request_id TEXT NOT NULL DEFAULT '',
  request_ip_hash TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT '',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  CHECK (action <> ''),
  CHECK (outcome IN ('success', 'denied', 'error', 'noop')),
  CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS admin_audit_log_time_idx
  ON admin_audit_log (occurred_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS admin_audit_log_actor_time_idx
  ON admin_audit_log (actor_id, occurred_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS admin_audit_log_action_time_idx
  ON admin_audit_log (action, occurred_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS admin_audit_log_tenant_page_time_idx
  ON admin_audit_log (tenant_id, page_id, occurred_at DESC, id DESC);

INSERT INTO admin_roles (name, description)
VALUES
  ('viewer', 'Read-only dashboard and bounded user detail access.'),
  ('support', 'Viewer plus legacy user state read access.'),
  ('maintainer', 'Support plus export and audit read access.'),
  ('owner', 'Full admin access, including future write and admin management permissions.')
ON CONFLICT (name) DO NOTHING;
