-- Phase 4 v1 internal notes schema proposal.
-- DO NOT apply to production without a fresh PostgreSQL backup, non-production
-- verification, production owner approval, and a reviewed rollout window.
-- This file is intentionally additive and idempotent.

CREATE TABLE IF NOT EXISTS internal_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'visible',
  created_by TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  hidden_by TEXT NOT NULL DEFAULT '',
  hidden_at TIMESTAMPTZ,
  hide_reason TEXT NOT NULL DEFAULT '',
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (target_type IN ('order', 'conversation', 'customer')),
  CHECK (target_id <> ''),
  CHECK (body <> ''),
  CHECK (char_length(body) <= 2000),
  CHECK (status IN ('visible', 'hidden'))
);

CREATE INDEX IF NOT EXISTS internal_notes_target_time_idx
  ON internal_notes (tenant_id, page_id, target_type, target_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS internal_notes_status_time_idx
  ON internal_notes (tenant_id, page_id, status, created_at DESC, id DESC);
