-- Phase 2 database schema draft.
-- Inert by design: this file is not loaded by runtime code and has not been
-- applied to any database. Backup /data before any future migration or adapter
-- switch.

CREATE TABLE IF NOT EXISTS profiles (
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  profile_pic TEXT NOT NULL DEFAULT '',
  raw_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, page_id, sender_id),
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (sender_id <> '')
);

CREATE TABLE IF NOT EXISTS conversations (
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  session_state TEXT NOT NULL DEFAULT '',
  last_product_code TEXT NOT NULL DEFAULT '',
  last_user_at TIMESTAMPTZ,
  handoff_until TIMESTAMPTZ,
  timed_out_at TIMESTAMPTZ,
  abandoned_order_draft JSONB NOT NULL DEFAULT '{}'::jsonb,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, page_id, sender_id),
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (sender_id <> '')
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  facebook_mid TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL,
  text TEXT NOT NULL DEFAULT '',
  parts JSONB NOT NULL DEFAULT '[]'::jsonb,
  source TEXT NOT NULL DEFAULT 'runtime',
  migration_source_key TEXT NOT NULL DEFAULT '',
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (sender_id <> ''),
  CHECK (role IN ('user', 'model', 'bot', 'system')),
  CHECK (jsonb_typeof(parts) = 'array')
);

CREATE INDEX IF NOT EXISTS messages_conversation_created_idx
  ON messages (tenant_id, page_id, sender_id, created_at, id);

CREATE UNIQUE INDEX IF NOT EXISTS messages_facebook_mid_unique_idx
  ON messages (tenant_id, page_id, facebook_mid)
  WHERE facebook_mid <> '';

CREATE UNIQUE INDEX IF NOT EXISTS messages_migration_source_unique_idx
  ON messages (tenant_id, page_id, source, migration_source_key)
  WHERE migration_source_key <> '';

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  product_code TEXT NOT NULL DEFAULT '',
  customer_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  draft_updated_at TIMESTAMPTZ,
  staff_notified_hash TEXT NOT NULL DEFAULT '',
  staff_notified_at TIMESTAMPTZ,
  abandoned_cart_reminder_sent_at TIMESTAMPTZ,
  abandoned_cart_reminder_idle_ms INTEGER,
  abandoned_cart_reminder_missing_fields TEXT[] NOT NULL DEFAULT '{}'::text[],
  abandoned_cart_reminder_failed_at TIMESTAMPTZ,
  abandoned_cart_reminder_failed_status INTEGER,
  abandoned_cart_reminder_failed_error VARCHAR(300) NOT NULL DEFAULT '',
  abandoned_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  sheet_dedupe_key TEXT NOT NULL DEFAULT '',
  product_interest TEXT NOT NULL DEFAULT '',
  migration_source_key TEXT NOT NULL DEFAULT '',
  raw_draft JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (sender_id <> ''),
  CHECK (status IN ('draft', 'ready_to_confirm', 'confirmed', 'cancelled', 'abandoned')),
  CHECK (abandoned_cart_reminder_idle_ms IS NULL OR abandoned_cart_reminder_idle_ms >= 0)
);

CREATE INDEX IF NOT EXISTS orders_user_status_idx
  ON orders (tenant_id, page_id, sender_id, status, updated_at);

CREATE UNIQUE INDEX IF NOT EXISTS orders_one_open_draft_per_user_idx
  ON orders (tenant_id, page_id, sender_id)
  WHERE status IN ('draft', 'ready_to_confirm');

CREATE UNIQUE INDEX IF NOT EXISTS orders_migration_source_unique_idx
  ON orders (tenant_id, page_id, migration_source_key)
  WHERE migration_source_key <> '';

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  item_index INTEGER NOT NULL DEFAULT 0,
  code TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  qty INTEGER NOT NULL DEFAULT 1,
  variant TEXT NOT NULL DEFAULT '',
  display TEXT NOT NULL DEFAULT '',
  raw_item JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (qty > 0),
  UNIQUE (order_id, item_index)
);

CREATE INDEX IF NOT EXISTS order_items_order_idx
  ON order_items (order_id, item_index);

CREATE INDEX IF NOT EXISTS order_items_tenant_page_idx
  ON order_items (tenant_id, page_id, code);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  sender_id TEXT NOT NULL DEFAULT '',
  event_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  type TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'runtime',
  migration_source_key TEXT NOT NULL DEFAULT '',
  session_state TEXT NOT NULL DEFAULT '',
  product_code TEXT NOT NULL DEFAULT '',
  text TEXT NOT NULL DEFAULT '',
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  customer_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  customer_history JSONB NOT NULL DEFAULT '[]'::jsonb,
  sheet_dedupe_key TEXT NOT NULL DEFAULT '',
  sheet_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (type <> ''),
  CHECK (source IN ('runtime', 'customer_export', 'sheet_outbox', 'admin', 'migration')),
  CHECK (jsonb_typeof(customer_history) = 'array')
);

CREATE INDEX IF NOT EXISTS events_tenant_page_time_idx
  ON events (tenant_id, page_id, event_at, id);

CREATE INDEX IF NOT EXISTS events_sender_time_idx
  ON events (tenant_id, page_id, sender_id, event_at, id);

CREATE INDEX IF NOT EXISTS events_type_time_idx
  ON events (tenant_id, page_id, type, event_at);

CREATE UNIQUE INDEX IF NOT EXISTS events_migration_source_unique_idx
  ON events (tenant_id, page_id, source, migration_source_key)
  WHERE migration_source_key <> '';

CREATE TABLE IF NOT EXISTS processed_mids (
  tenant_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  mid TEXT NOT NULL,
  sender_id TEXT NOT NULL DEFAULT '',
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (tenant_id, page_id, mid),
  CHECK (tenant_id <> ''),
  CHECK (page_id <> ''),
  CHECK (mid <> '')
);

CREATE INDEX IF NOT EXISTS processed_mids_first_seen_idx
  ON processed_mids (tenant_id, page_id, first_seen_at);
